- name: Check if the composer installer exists
  ansible.builtin.stat:
    path: "/tmp/composer-installer.php"
  register: composer_check

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
  when: not composer_check.stat.exists

- name: Run Composer installer
  shell: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  when: not composer_check.stat.exists

  