- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php

- name: Run Composer installer
  shell: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer