- name: Add MySQL 5.7 APT repository
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-5.7"
    state: present
    validate_certs: yes
    keyserver: keys.gnupg.net
    key_id: "8C718D3B5072E1F5"

- name: Update package cache
  apt:
    update_cache: yes

- name: Install MySQL 5.7
  apt:
    name: mysql-server-5.7
    state: present


- name: Create admin user
  mysql_user:
    name: "{{sql_admin_user}}"
    password: "{{sql_admin_password}}"
    priv: "*.*:ALL,GRANT"
    append_privs: yes
    state: present
  no_log: True