- name: Add PPA for PHP 8.1
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update package cache
  apt:
    update_cache: yes

- name: Install PHP 8.1 and related packages
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-common
      - php8.1-curl
      - php8.1-gd
      - php8.1-json
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-opcache
      - php8.1-readline
      - php8.1-xml
      - php8.1-zip
    state: present