- name: Add PPA for PHP 8.1
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP 8.1 and related packages
  apt:
    name:
      - php8.1
      - php8.1-cli
      - php8.1-common
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-mysql
    state: present
    update_cache: yes