- name: Deploy Docker container
  hosts: dot-hiring
  become: true
  vars:
    mysql_root_password: "r00tP455"
    sql_admin_user: "dot-user"
    sql_admin_password: "d0tp455w0rd"
  tasks:
  - name: create mysql user
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ sql_admin_user }}"
      password: "{{ sql_admin_password }}"
      priv: '*.*:ALL'
      state: present

  - name: create mysql database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: laravel_starter
      state: present

  - name: Allow remote connection into mysql
    become: yes
    shell: sudo sed -i 's/bind-address    = 127.0.0.1/bind-address    = 0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  
  - name: restart mysql service
    become: yes
    shell: systemctl restart mysql

  - name: Create MySQL remote user
    become: yes
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "remote-user"
      password: "remote-user-P455"
      host: "%"
      priv: '*.*:ALL,GRANT'