- name: Setup server environment 
  hosts: dot-hiring
  become: yes
  roles:
    - name: setup-env
  vars:
    mysql_root_password: "r00tP455"
    sql_admin_user: "dot-user"
    sql_admin_password: "d0tp455w0rd"