# - name: Create a src directory
#   become: yes
#   file:
#     path: "{{ app_dir }}"
#     state: directory
#     mode: '0777'

- name: Install certbot
  become: yes 
  apt: 
    name: 
      - certbot
      - software-properties-common
      - php8.1-fpm
    state: latest